//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yp_gorlanov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class answers
    {
        public int answer_id { get; set; }
        public int question_id { get; set; }
        public string answer_text { get; set; }
        public Nullable<bool> is_correct { get; set; }
    
        public virtual questions questions { get; set; }
    }
}
