//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yp_gorlanov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class marks
    {
        public int mark_id { get; set; }
        public int test_id { get; set; }
        public int student_id { get; set; }
        public int mark { get; set; }
    
        public virtual students students { get; set; }
        public virtual test test { get; set; }
    }
}
