//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yp_gorlanov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public Nullable<int> student_card { get; set; }
        public Nullable<int> group_number { get; set; }
        public int role_id { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual roles roles { get; set; }
    }
}
